[package]
name = "blusc"
version = "0.0.1"
authors = ["Mark"]
edition = "2021"
license-file = "c-blosc2/LICENSE.txt"
exclude = [
    "c-blosc2/**",
    "reference/**",
]
repository = "https://github.com/keller-mark/blusc"
keywords = ["compression"]
categories = ["compression"]
description = "Pure rust implementation for blosc"

[dependencies]
lz4_flex = "0.12.0"
snap = "1.1.1"
ruzstd = "0.8.2"
flate2 = "1.1.5"

[dev-dependencies]
# ONLY FOR TESTING THAT THE RUST IMPLEMENTATION MATCHES THE C BINDINGS
# Reference: https://github.com/maiteko/blosc2-src-rs
blosc2-src = "0.1.4"
bytemuck = { version = "1.14.0", features = ["extern_crate_alloc", "must_cast", "min_const_generics"] }
bytes = "1.7.0"