[package]
name = "blusc"
version = "0.0.1"
authors = ["Mark"]
edition = "2021"
license-file = "c-blosc2/LICENSE.txt"
exclude = [
    "c-blosc2/**",
    "reference/**",
]
repository = "https://github.com/keller-mark/blusc"
keywords = ["compression"]
categories = ["compression"]
description = "Pure rust implementation for blosc"

[dependencies]
lz4_flex = "0.12.0"
snap = "1.1.1"
ruzstd = "0.8.2"
